// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1slXonAQNYKJ96Bnwotvgx2Od9ae9v4',
    appId: '1:118023465186:web:fc69196d0638b3e73016bb',
    messagingSenderId: '118023465186',
    projectId: 'hackletes-cb7cd',
    authDomain: 'hackletes-cb7cd.firebaseapp.com',
    storageBucket: 'hackletes-cb7cd.firebasestorage.app',
    measurementId: 'G-Z2XHLW846H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwivDSUNAUKVUQIeaZyOpGyYPWL19fAdU',
    appId: '1:118023465186:android:b1d637ed64ed0ae43016bb',
    messagingSenderId: '118023465186',
    projectId: 'hackletes-cb7cd',
    storageBucket: 'hackletes-cb7cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrrIOkW1NGDVkOItWDcAdAYDvov6ugdws',
    appId: '1:118023465186:ios:698ace18fa33163f3016bb',
    messagingSenderId: '118023465186',
    projectId: 'hackletes-cb7cd',
    storageBucket: 'hackletes-cb7cd.firebasestorage.app',
    androidClientId: '118023465186-ppntmjsno7l4d063eso47nvs2sd3ctj6.apps.googleusercontent.com',
    iosClientId: '118023465186-0t5dbnrsrlg7ps2k7r99a3b0mm1daemo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sihUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrrIOkW1NGDVkOItWDcAdAYDvov6ugdws',
    appId: '1:118023465186:ios:698ace18fa33163f3016bb',
    messagingSenderId: '118023465186',
    projectId: 'hackletes-cb7cd',
    storageBucket: 'hackletes-cb7cd.firebasestorage.app',
    androidClientId: '118023465186-ppntmjsno7l4d063eso47nvs2sd3ctj6.apps.googleusercontent.com',
    iosClientId: '118023465186-0t5dbnrsrlg7ps2k7r99a3b0mm1daemo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sihUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc1slXonAQNYKJ96Bnwotvgx2Od9ae9v4',
    appId: '1:118023465186:web:4a4bab12b1ed7c883016bb',
    messagingSenderId: '118023465186',
    projectId: 'hackletes-cb7cd',
    authDomain: 'hackletes-cb7cd.firebaseapp.com',
    storageBucket: 'hackletes-cb7cd.firebasestorage.app',
    measurementId: 'G-WPSEJV7GLR',
  );
}
